services:
  framework.microservicesmanagerapi:
    image: ${DOCKER_REGISTRY-}frameworkmicroservicesmanagerapi
    build:
      context: .
      dockerfile: Framework.MicroservicesManagerApi/Dockerfile
    environment:
      - RABBITMQ__HOST=rabbitmq
      - RABBITMQ__PORT=5672
    
  framework.filestorageapi:
    image: ${DOCKER_REGISTRY-}frameworkfilestorageapi
    build:
      context: .
      dockerfile: Framework.FileStorageApi/Dockerfile
    environment:
      - RABBITMQ__HOST=rabbitmq
      - RABBITMQ__PORT=5672

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  rabbitmq_data:
